/* ============================================================
   THE REFLECTIVE — World Cup 2026 Schedule & Predictor
   Tournament data
   ------------------------------------------------------------
   Kick-off times are anchored in US Eastern Time (EDT, UTC-4),
   exactly as published by FIFA / USA TODAY. The app converts
   every kick-off to Gulf Standard Time (Asia/Dubai, UTC+4)
   at render time, so UAE time = ET + 8 hours, always correct.
   Matches that begin after midnight ET are stored on the
   correct ET calendar day with hour 0.
   ============================================================ */

const TEAMS = {
  MEX: { name: "Mexico", flag: "🇲🇽" },
  RSA: { name: "South Africa", flag: "🇿🇦" },
  KOR: { name: "South Korea", flag: "🇰🇷" },
  CZE: { name: "Czechia", flag: "🇨🇿" },
  SUI: { name: "Switzerland", flag: "🇨🇭" },
  CAN: { name: "Canada", flag: "🇨🇦" },
  QAT: { name: "Qatar", flag: "🇶🇦" },
  BIH: { name: "Bosnia & Herzegovina", flag: "🇧🇦" },
  BRA: { name: "Brazil", flag: "🇧🇷" },
  MAR: { name: "Morocco", flag: "🇲🇦" },
  HAI: { name: "Haiti", flag: "🇭🇹" },
  SCO: { name: "Scotland", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  USA: { name: "United States", flag: "🇺🇸" },
  TUR: { name: "Türkiye", flag: "🇹🇷" },
  AUS: { name: "Australia", flag: "🇦🇺" },
  PAR: { name: "Paraguay", flag: "🇵🇾" },
  GER: { name: "Germany", flag: "🇩🇪" },
  ECU: { name: "Ecuador", flag: "🇪🇨" },
  CIV: { name: "Ivory Coast", flag: "🇨🇮" },
  CUW: { name: "Curaçao", flag: "🇨🇼" },
  NED: { name: "Netherlands", flag: "🇳🇱" },
  JPN: { name: "Japan", flag: "🇯🇵" },
  SWE: { name: "Sweden", flag: "🇸🇪" },
  TUN: { name: "Tunisia", flag: "🇹🇳" },
  BEL: { name: "Belgium", flag: "🇧🇪" },
  EGY: { name: "Egypt", flag: "🇪🇬" },
  IRN: { name: "Iran", flag: "🇮🇷" },
  NZL: { name: "New Zealand", flag: "🇳🇿" },
  ESP: { name: "Spain", flag: "🇪🇸" },
  CPV: { name: "Cape Verde", flag: "🇨🇻" },
  KSA: { name: "Saudi Arabia", flag: "🇸🇦" },
  URU: { name: "Uruguay", flag: "🇺🇾" },
  FRA: { name: "France", flag: "🇫🇷" },
  SEN: { name: "Senegal", flag: "🇸🇳" },
  IRQ: { name: "Iraq", flag: "🇮🇶" },
  NOR: { name: "Norway", flag: "🇳🇴" },
  ARG: { name: "Argentina", flag: "🇦🇷" },
  ALG: { name: "Algeria", flag: "🇩🇿" },
  AUT: { name: "Austria", flag: "🇦🇹" },
  JOR: { name: "Jordan", flag: "🇯🇴" },
  POR: { name: "Portugal", flag: "🇵🇹" },
  COD: { name: "DR Congo", flag: "🇨🇩" },
  UZB: { name: "Uzbekistan", flag: "🇺🇿" },
  COL: { name: "Colombia", flag: "🇨🇴" },
  ENG: { name: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  CRO: { name: "Croatia", flag: "🇭🇷" },
  GHA: { name: "Ghana", flag: "🇬🇭" },
  PAN: { name: "Panama", flag: "🇵🇦" },
};

const GROUPS = {
  A: ["MEX", "KOR", "CZE", "RSA"],
  B: ["SUI", "CAN", "QAT", "BIH"],
  C: ["BRA", "MAR", "HAI", "SCO"],
  D: ["USA", "TUR", "AUS", "PAR"],
  E: ["GER", "ECU", "CIV", "CUW"],
  F: ["NED", "JPN", "SWE", "TUN"],
  G: ["BEL", "EGY", "IRN", "NZL"],
  H: ["ESP", "CPV", "KSA", "URU"],
  I: ["FRA", "SEN", "IRQ", "NOR"],
  J: ["ARG", "ALG", "AUT", "JOR"],
  K: ["POR", "COD", "UZB", "COL"],
  L: ["ENG", "CRO", "GHA", "PAN"],
};

/* et: [year, month(1-12), day, hour(0-23), minute] in US Eastern (EDT) */
const GROUP_MATCHES = [
  { g: "A", h: "MEX", a: "RSA", et: [2026,6,11,15,0], venue: "Estadio Azteca", city: "Mexico City" },
  { g: "A", h: "KOR", a: "CZE", et: [2026,6,11,22,0], venue: "Estadio Akron", city: "Guadalajara" },
  { g: "B", h: "CAN", a: "BIH", et: [2026,6,12,15,0], venue: "BMO Field", city: "Toronto" },
  { g: "D", h: "USA", a: "PAR", et: [2026,6,12,21,0], venue: "SoFi Stadium", city: "Los Angeles" },
  { g: "C", h: "BRA", a: "MAR", et: [2026,6,13,15,0], venue: "MetLife Stadium", city: "New York / NJ" },
  { g: "D", h: "AUS", a: "TUR", et: [2026,6,13,18,0], venue: "BC Place", city: "Vancouver" },
  { g: "C", h: "HAI", a: "SCO", et: [2026,6,13,21,0], venue: "Gillette Stadium", city: "Boston" },
  { g: "B", h: "QAT", a: "SUI", et: [2026,6,14,0,0], venue: "Levi's Stadium", city: "San Francisco Bay" },
  { g: "E", h: "GER", a: "CUW", et: [2026,6,14,13,0], venue: "NRG Stadium", city: "Houston" },
  { g: "E", h: "CIV", a: "ECU", et: [2026,6,14,16,0], venue: "Lincoln Financial Field", city: "Philadelphia" },
  { g: "F", h: "NED", a: "JPN", et: [2026,6,14,19,0], venue: "AT&T Stadium", city: "Dallas" },
  { g: "F", h: "SWE", a: "TUN", et: [2026,6,14,22,0], venue: "Estadio BBVA", city: "Monterrey" },
  { g: "H", h: "ESP", a: "CPV", et: [2026,6,15,12,0], venue: "Mercedes-Benz Stadium", city: "Atlanta" },
  { g: "G", h: "BEL", a: "EGY", et: [2026,6,15,15,0], venue: "Lumen Field", city: "Seattle" },
  { g: "H", h: "KSA", a: "URU", et: [2026,6,15,18,0], venue: "Hard Rock Stadium", city: "Miami" },
  { g: "G", h: "IRN", a: "NZL", et: [2026,6,15,21,0], venue: "SoFi Stadium", city: "Los Angeles" },
  { g: "I", h: "FRA", a: "SEN", et: [2026,6,16,15,0], venue: "MetLife Stadium", city: "New York / NJ" },
  { g: "I", h: "IRQ", a: "NOR", et: [2026,6,16,18,0], venue: "Gillette Stadium", city: "Boston" },
  { g: "J", h: "ARG", a: "ALG", et: [2026,6,16,21,0], venue: "Arrowhead Stadium", city: "Kansas City" },
  { g: "J", h: "AUT", a: "JOR", et: [2026,6,17,0,0], venue: "Levi's Stadium", city: "San Francisco Bay" },
  { g: "K", h: "POR", a: "COD", et: [2026,6,17,13,0], venue: "NRG Stadium", city: "Houston" },
  { g: "L", h: "ENG", a: "CRO", et: [2026,6,17,16,0], venue: "AT&T Stadium", city: "Dallas" },
  { g: "L", h: "GHA", a: "PAN", et: [2026,6,17,19,0], venue: "BMO Field", city: "Toronto" },
  { g: "K", h: "UZB", a: "COL", et: [2026,6,17,22,0], venue: "Estadio Azteca", city: "Mexico City" },
  { g: "A", h: "CZE", a: "RSA", et: [2026,6,18,12,0], venue: "Mercedes-Benz Stadium", city: "Atlanta" },
  { g: "B", h: "SUI", a: "BIH", et: [2026,6,18,15,0], venue: "SoFi Stadium", city: "Los Angeles" },
  { g: "B", h: "CAN", a: "QAT", et: [2026,6,18,18,0], venue: "BC Place", city: "Vancouver" },
  { g: "A", h: "MEX", a: "KOR", et: [2026,6,18,21,0], venue: "Estadio Akron", city: "Guadalajara" },
  { g: "D", h: "USA", a: "AUS", et: [2026,6,19,15,0], venue: "Lumen Field", city: "Seattle" },
  { g: "C", h: "SCO", a: "MAR", et: [2026,6,19,18,0], venue: "Gillette Stadium", city: "Boston" },
  { g: "C", h: "BRA", a: "HAI", et: [2026,6,19,21,0], venue: "Lincoln Financial Field", city: "Philadelphia" },
  { g: "D", h: "TUR", a: "PAR", et: [2026,6,20,0,0], venue: "Levi's Stadium", city: "San Francisco Bay" },
  { g: "F", h: "NED", a: "SWE", et: [2026,6,20,13,0], venue: "NRG Stadium", city: "Houston" },
  { g: "E", h: "GER", a: "CIV", et: [2026,6,20,16,0], venue: "BMO Field", city: "Toronto" },
  { g: "E", h: "ECU", a: "CUW", et: [2026,6,20,20,0], venue: "Arrowhead Stadium", city: "Kansas City" },
  { g: "F", h: "TUN", a: "JPN", et: [2026,6,21,0,0], venue: "Estadio BBVA", city: "Monterrey" },
  { g: "H", h: "ESP", a: "KSA", et: [2026,6,21,12,0], venue: "Mercedes-Benz Stadium", city: "Atlanta" },
  { g: "G", h: "BEL", a: "IRN", et: [2026,6,21,15,0], venue: "SoFi Stadium", city: "Los Angeles" },
  { g: "H", h: "URU", a: "CPV", et: [2026,6,21,18,0], venue: "Hard Rock Stadium", city: "Miami" },
  { g: "G", h: "NZL", a: "EGY", et: [2026,6,21,21,0], venue: "BC Place", city: "Vancouver" },
  { g: "J", h: "ARG", a: "AUT", et: [2026,6,22,13,0], venue: "AT&T Stadium", city: "Dallas" },
  { g: "I", h: "FRA", a: "IRQ", et: [2026,6,22,17,0], venue: "Lincoln Financial Field", city: "Philadelphia" },
  { g: "I", h: "NOR", a: "SEN", et: [2026,6,22,20,0], venue: "MetLife Stadium", city: "New York / NJ" },
  { g: "J", h: "JOR", a: "ALG", et: [2026,6,22,23,0], venue: "Levi's Stadium", city: "San Francisco Bay" },
  { g: "K", h: "POR", a: "UZB", et: [2026,6,23,13,0], venue: "NRG Stadium", city: "Houston" },
  { g: "L", h: "ENG", a: "GHA", et: [2026,6,23,16,0], venue: "Gillette Stadium", city: "Boston" },
  { g: "L", h: "PAN", a: "CRO", et: [2026,6,23,19,0], venue: "BMO Field", city: "Toronto" },
  { g: "K", h: "COL", a: "COD", et: [2026,6,23,22,0], venue: "Estadio Akron", city: "Guadalajara" },
  { g: "B", h: "CAN", a: "SUI", et: [2026,6,24,15,0], venue: "BC Place", city: "Vancouver" },
  { g: "B", h: "BIH", a: "QAT", et: [2026,6,24,15,0], venue: "Lumen Field", city: "Seattle" },
  { g: "C", h: "SCO", a: "BRA", et: [2026,6,24,18,0], venue: "Hard Rock Stadium", city: "Miami" },
  { g: "C", h: "MAR", a: "HAI", et: [2026,6,24,18,0], venue: "Mercedes-Benz Stadium", city: "Atlanta" },
  { g: "A", h: "MEX", a: "CZE", et: [2026,6,24,21,0], venue: "Estadio Azteca", city: "Mexico City" },
  { g: "A", h: "KOR", a: "RSA", et: [2026,6,24,21,0], venue: "Estadio BBVA", city: "Monterrey" },
  { g: "E", h: "ECU", a: "GER", et: [2026,6,25,16,0], venue: "MetLife Stadium", city: "New York / NJ" },
  { g: "E", h: "CUW", a: "CIV", et: [2026,6,25,16,0], venue: "Lincoln Financial Field", city: "Philadelphia" },
  { g: "F", h: "TUN", a: "NED", et: [2026,6,25,19,0], venue: "Arrowhead Stadium", city: "Kansas City" },
  { g: "F", h: "JPN", a: "SWE", et: [2026,6,25,19,0], venue: "AT&T Stadium", city: "Dallas" },
  { g: "D", h: "USA", a: "TUR", et: [2026,6,25,22,0], venue: "SoFi Stadium", city: "Los Angeles" },
  { g: "D", h: "PAR", a: "AUS", et: [2026,6,25,22,0], venue: "Levi's Stadium", city: "San Francisco Bay" },
  { g: "H", h: "CPV", a: "KSA", et: [2026,6,26,13,0], venue: "NRG Stadium", city: "Houston" },
  { g: "I", h: "NOR", a: "FRA", et: [2026,6,26,15,0], venue: "Gillette Stadium", city: "Boston" },
  { g: "I", h: "SEN", a: "IRQ", et: [2026,6,26,15,0], venue: "BMO Field", city: "Toronto" },
  { g: "G", h: "NZL", a: "BEL", et: [2026,6,26,20,0], venue: "BC Place", city: "Vancouver" },
  { g: "G", h: "EGY", a: "IRN", et: [2026,6,26,20,0], venue: "Lumen Field", city: "Seattle" },
  { g: "H", h: "URU", a: "ESP", et: [2026,6,26,23,0], venue: "Estadio Akron", city: "Guadalajara" },
  { g: "L", h: "PAN", a: "ENG", et: [2026,6,27,17,0], venue: "MetLife Stadium", city: "New York / NJ" },
  { g: "L", h: "CRO", a: "GHA", et: [2026,6,27,17,0], venue: "Lincoln Financial Field", city: "Philadelphia" },
  { g: "K", h: "COL", a: "POR", et: [2026,6,27,19,30], venue: "Hard Rock Stadium", city: "Miami" },
  { g: "K", h: "COD", a: "UZB", et: [2026,6,27,19,30], venue: "Mercedes-Benz Stadium", city: "Atlanta" },
  { g: "J", h: "JOR", a: "ARG", et: [2026,6,27,22,0], venue: "AT&T Stadium", city: "Dallas" },
  { g: "J", h: "ALG", a: "AUT", et: [2026,6,27,22,0], venue: "Arrowhead Stadium", city: "Kansas City" },
];

/* Knockout rounds. Pairings are filled in by the predictor.
   Dates/venues are the published 2026 schedule; exact kick-off
   clock times are confirmed by FIFA closer to each round, so the
   schedule view shows the match date in UAE terms. */
const KNOCKOUT = {
  R32: {
    label: "Round of 32",
    dateRange: "28 Jun – 3 Jul",
    matches: [
      { id: "R32-1", date: [2026,6,28], city: "Los Angeles", venue: "SoFi Stadium" },
      { id: "R32-2", date: [2026,6,28], city: "Houston", venue: "NRG Stadium" },
      { id: "R32-3", date: [2026,6,29], city: "Boston", venue: "Gillette Stadium" },
      { id: "R32-4", date: [2026,6,29], city: "Monterrey", venue: "Estadio BBVA" },
      { id: "R32-5", date: [2026,6,29], city: "Mexico City", venue: "Estadio Azteca" },
      { id: "R32-6", date: [2026,6,30], city: "Dallas", venue: "AT&T Stadium" },
      { id: "R32-7", date: [2026,6,30], city: "Seattle", venue: "Lumen Field" },
      { id: "R32-8", date: [2026,6,30], city: "Atlanta", venue: "Mercedes-Benz Stadium" },
      { id: "R32-9", date: [2026,7,1], city: "Los Angeles", venue: "SoFi Stadium" },
      { id: "R32-10", date: [2026,7,1], city: "Vancouver", venue: "BC Place" },
      { id: "R32-11", date: [2026,7,1], city: "Guadalajara", venue: "Estadio Akron" },
      { id: "R32-12", date: [2026,7,2], city: "New York / NJ", venue: "MetLife Stadium" },
      { id: "R32-13", date: [2026,7,2], city: "Philadelphia", venue: "Lincoln Financial Field" },
      { id: "R32-14", date: [2026,7,2], city: "Kansas City", venue: "Arrowhead Stadium" },
      { id: "R32-15", date: [2026,7,3], city: "Miami", venue: "Hard Rock Stadium" },
      { id: "R32-16", date: [2026,7,3], city: "San Francisco Bay", venue: "Levi's Stadium" },
    ],
  },
  R16: {
    label: "Round of 16",
    dateRange: "4 Jul – 7 Jul",
    matches: [
      { id: "R16-1", date: [2026,7,4], city: "Philadelphia", venue: "Lincoln Financial Field" },
      { id: "R16-2", date: [2026,7,4], city: "Houston", venue: "NRG Stadium" },
      { id: "R16-3", date: [2026,7,5], city: "Mexico City", venue: "Estadio Azteca" },
      { id: "R16-4", date: [2026,7,5], city: "Dallas", venue: "AT&T Stadium" },
      { id: "R16-5", date: [2026,7,6], city: "Seattle", venue: "Lumen Field" },
      { id: "R16-6", date: [2026,7,6], city: "Atlanta", venue: "Mercedes-Benz Stadium" },
      { id: "R16-7", date: [2026,7,7], city: "Vancouver", venue: "BC Place" },
      { id: "R16-8", date: [2026,7,7], city: "New York / NJ", venue: "MetLife Stadium" },
    ],
  },
  QF: {
    label: "Quarter-finals",
    dateRange: "9 Jul – 11 Jul",
    matches: [
      { id: "QF-1", date: [2026,7,9], city: "Boston", venue: "Gillette Stadium" },
      { id: "QF-2", date: [2026,7,10], city: "Los Angeles", venue: "SoFi Stadium" },
      { id: "QF-3", date: [2026,7,11], city: "Kansas City", venue: "Arrowhead Stadium" },
      { id: "QF-4", date: [2026,7,11], city: "Miami", venue: "Hard Rock Stadium" },
    ],
  },
  SF: {
    label: "Semi-finals",
    dateRange: "14 Jul – 15 Jul",
    matches: [
      { id: "SF-1", date: [2026,7,14], city: "Dallas", venue: "AT&T Stadium" },
      { id: "SF-2", date: [2026,7,15], city: "Atlanta", venue: "Mercedes-Benz Stadium" },
    ],
  },
  TP: {
    label: "Third-place play-off",
    dateRange: "18 Jul",
    matches: [
      { id: "TP-1", date: [2026,7,18], city: "Miami", venue: "Hard Rock Stadium" },
    ],
  },
  FIN: {
    label: "Final",
    dateRange: "19 Jul",
    matches: [
      { id: "FIN-1", date: [2026,7,19], city: "New York / NJ", venue: "MetLife Stadium" },
    ],
  },
};

/* How each knockout match is fed. Slots reference group finishers
   (e.g. "1A" = winner of Group A, "2B" = runner-up of Group B,
   "3?" = a best-third-placed team you assign) or the winner of a
   previous tie ("WR32-1"). This mirrors FIFA's published bracket
   flow; third-place destinations are yours to assign. */
const BRACKET = {
  "R32-1":  { home: "1A", away: "3CEFI" },
  "R32-2":  { home: "1C", away: "2F" },
  "R32-3":  { home: "1F", away: "2C" },
  "R32-4":  { home: "1I", away: "3BEHK" },
  "R32-5":  { home: "1E", away: "3ABFI" },
  "R32-6":  { home: "1L", away: "3DGHJ" },
  "R32-7":  { home: "1D", away: "2G" },
  "R32-8":  { home: "1G", away: "2A" },
  "R32-9":  { home: "1H", away: "3BCFG" },
  "R32-10": { home: "1B", away: "3EFGI" },
  "R32-11": { home: "1J", away: "2H" },
  "R32-12": { home: "1K", away: "3DEIL" },
  "R32-13": { home: "2E", away: "2I" },
  "R32-14": { home: "2K", away: "2L" },
  "R32-15": { home: "2B", away: "2J" },
  "R32-16": { home: "2D", away: "3ACDH" },

  "R16-1":  { home: "WR32-1", away: "WR32-2" },
  "R16-2":  { home: "WR32-3", away: "WR32-4" },
  "R16-3":  { home: "WR32-5", away: "WR32-6" },
  "R16-4":  { home: "WR32-7", away: "WR32-8" },
  "R16-5":  { home: "WR32-9", away: "WR32-10" },
  "R16-6":  { home: "WR32-11", away: "WR32-12" },
  "R16-7":  { home: "WR32-13", away: "WR32-14" },
  "R16-8":  { home: "WR32-15", away: "WR32-16" },

  "QF-1": { home: "WR16-1", away: "WR16-2" },
  "QF-2": { home: "WR16-3", away: "WR16-4" },
  "QF-3": { home: "WR16-5", away: "WR16-6" },
  "QF-4": { home: "WR16-7", away: "WR16-8" },

  "SF-1": { home: "WQF-1", away: "WQF-2" },
  "SF-2": { home: "WQF-3", away: "WQF-4" },

  "TP-1":  { home: "LSF-1", away: "LSF-2" },
  "FIN-1": { home: "WSF-1", away: "WSF-2" },
};

window.WC = { TEAMS, GROUPS, GROUP_MATCHES, KNOCKOUT, BRACKET };
